Limit 3C and CM3S IO HDMI resolution
radxa/kernel pull request #145
Opened 2023-06-29 08:11 UTC by vamrs-feng

2023-06-29 08:44 UTC, RadxaYuntian reviewed
还是老问题，@RadxaStephen决定吧

2023-06-29 08:44 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	if ((of_machine_is_compatible("radxa,rock-3c")) ||
最好还是在设备树里面加一个额外的flag而不是匹配产品名

2023-06-29 08:44 UTC, RadxaYuntian commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +#include <linux/rockchip/cpu.h>
应该保留已有的空行

2023-06-29 08:44 UTC, RadxaYuntian commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +		if ((mode->hdisplay > 1920) || (mode->vdisplay > 1080)) {
竖屏1080x1920就没法显示了

2023-06-29 08:45 UTC, RadxaYuntian commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +		if ((mode->hdisplay > 1920) || (mode->vdisplay > 1080)) {
应该按照总像素数量来判断

2023-06-29 08:48 UTC, vamrs-feng commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +#include <linux/rockchip/cpu.h>
那要不这个PR先缓一缓，优化一下再提？

2023-06-29 08:50 UTC, vamrs-feng commented
那要等后续优化一下再提还是先提再优化？

2023-06-29 08:52 UTC, RadxaStephen commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +		if ((mode->hdisplay > 1920) || (mode->vdisplay > 1080)) {
再加这个 https://github.com/radxa/kernel/commit/84dfaa3a573c2c1539fbab7d44a08123092e0071

2023-06-29 09:12 UTC, RadxaStephen commented
再优化一下。

2023-06-30 02:23 UTC, vamrs-feng commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	if ((of_machine_is_compatible("radxa,rock-3c")) ||
```c
&hdmi {
	status = "okay";
	resolution_limit;
};
```

我打算在这里加个字段作为标识，怎么样？

2023-06-30 02:25 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	if ((of_machine_is_compatible("radxa,rock-3c")) ||
dtb overlay是不能删除flag的。如果是布尔值那就没法关闭这个选项。

2023-06-30 02:31 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	if ((of_machine_is_compatible("radxa,rock-3c")) ||
具体的昨天在企业微信群里面说了。傻逼腾讯不能复制内容，你自己搜preferred_hdisplay搜一下吧

2023-06-30 06:36 UTC, vamrs-feng commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	if ((of_machine_is_compatible("radxa,rock-3c")) ||
意思是可以通过设置 preferred_hdisplay =<1920>; preferred_hdisplay =<1080>;这样的形式自定限制的分辨率是吗。如果只需要判断要不要限制（1080P）的话，我就只加一个字段resolution_limit = <1>。

2023-06-30 07:12 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	if ((of_machine_is_compatible("radxa,rock-3c")) ||
两个字段可以实现数据和代码的分离，不然你现在需要在驱动里面硬编码fhd分辨率。而且如果后面不同的设备有不同的分辨率限制的话也不好实现。

2023-06-30 07:13 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	if ((of_machine_is_compatible("radxa,rock-3c")) ||
可以用of_property_read_u32,在出错或者读取到0的时候跳过相关的限制。

2023-07-04 02:43 UTC, RadxaYuntian requested changes

2023-07-04 02:43 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	root_node = of_find_node_by_path("/");
获取初始值应该在dw_hdmi_probe函数里面实现，用np指针获取，将结果保存到hdmi结构里面

2023-07-04 02:43 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +						snprintf(resol_name,sizeof(resol_name),"%dx%d",preset_max_hdisplay,preset_max_vdisplay);
这个可以放到循环外面

2023-07-04 02:43 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +					if (!strcmp(mode->name, preferred_mode->name)) {
这里可下面的if可以合并，然后直接对比hdisplay和vdisplay

2023-07-06 10:31 UTC, RadxaYuntian commented
之前review的都还没修改

2023-07-07 06:49 UTC, RadxaYuntian requested changes

2023-07-07 06:49 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	 * ROCK 3C and Radxa CM3S IO HDMI port with resolutions up to 1080P@60fps.
```suggestion
	 * Override max resolution
```

2023-07-07 06:49 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +		}
```suggestion
	if (hdmi->preset_max_hdisplay && hdmi->preset_max_vdisplay) {
		list_for_each_entry(mode, &connector->probed_modes, head) {
			if (mode->hdisplay == hdmi->preset_max_hdisplay &&
			mode->vdisplay == hdmi->preset_max_vdisplay) {
				if (!preferred_mode ||
				 (drm_mode_vrefresh(mode) > drm_mode_vrefresh(preferred_mode) &&
				 drm_mode_vrefresh(mode) <= 60) ) {
					preferred_mode = mode;
				}
			}
		}
```

2023-07-07 06:49 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	memset(resol_name,'\0',sizeof(resol_name));
```suggestion
```
都用不上

2023-07-07 06:49 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +		}
格式还要调一下，github上不好对齐缩进

2023-07-07 06:49 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	hdmi->preset_max_vdisplay = 0;
```suggestion
```
`devm_kzalloc`会0初始化

2023-07-07 06:49 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	of_property_read_u32(np,"preset_max_vdisplay",&hdmi->preset_max_vdisplay);
```suggestion
	of_property_read_u32(np, "preset_max_hdisplay", &hdmi->preset_max_hdisplay);
	of_property_read_u32(np, "preset_max_vdisplay", &hdmi->preset_max_vdisplay);
```
逗号后面要有空格

2023-07-07 06:49 UTC, RadxaYuntian commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +	if ((hdmi->preset_max_hdisplay!= 0) && (hdmi->preset_max_vdisplay!= 0)) {
这里应该可以直接从`dw_hdmi`参数里面获得这两个值，不需要在前面去解析dts

2023-07-07 07:03 UTC, vamrs-feng commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +	if ((hdmi->preset_max_hdisplay!= 0) && (hdmi->preset_max_vdisplay!= 0)) {
这里好像不能这样做，直接使用dw_hdmi里面的两个值会报错，他结构体不是定义在头文件，我试过了。

2023-07-07 07:18 UTC, RadxaYuntian commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +	if ((hdmi->preset_max_hdisplay!= 0) && (hdmi->preset_max_vdisplay!= 0)) {
那就应该在`dw-hdmi.c`里面添加一个导出的`bool dw_hdmi_resolution_within_custom_limit(struct dw_hdmi *dw_hdmi, unsigned int x, unsigned int y)`的函数，然后在这里调用

2023-07-07 11:21 UTC, RadxaYuntian requested changes

2023-07-07 11:21 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +bool dw_hdmi_resolution_within_custom_limit(struct dw_hdmi *dw_hdmi,
我当时的意思是直接传值mode->hdisplay，然后和dw_hdmi里面的总像素数对比，如果是范围内就返回true，而不是让你传指针再写回去……

2023-07-07 11:21 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +		snprintf(resol_name,sizeof(resol_name),"%dx%d",
所以既然这个`resol_name`就是`hdmi->preset_max_hdisplay`和`hdmi->preset_max_vdisplay`那么为什么不直接对比这两个值，反而要变成字符串再去对比

2023-07-07 11:21 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +						if (!strcmp(mode->name, resol_name))
我感觉这边应该是必为真，因为你前面已经有`mode->hdisplay == hdmi->preset_max_hdisplay && mode->vdisplay == hdmi->preset_max_vdisplay`的判断了
所以还是为什么非要把同一个值转成字符串再对比

2023-07-07 11:21 UTC, RadxaYuntian commented on drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c
> +extern bool dw_hdmi_resolution_within_custom_limit(struct dw_hdmi *dw_hdmi,
这个应该是定义在`dw_hdmi.h`里面的

2023-07-10 07:11 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +	return true;
```suggestion
	return !dw_hdmi->preset_max_hdisplay ||
		!dw_hdmi->preset_max_hdisplay ||
		hdisplay * vdisplay <= dw_hdmi->preset_max_hdisplay * dw_hdmi->preset_max_vdisplay;
```
这种多层的if以后可以展开

2023-07-10 07:13 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +		snprintf(resol_name,sizeof(resol_name),"%dx%d",
@vamrs-feng 说是为了避免选择60i模式，那可以通过检查`mode->flag`有没有[`DRM_MODE_FLAG_INTERLACE`](https://elixir.bootlin.com/linux/latest/source/include/drm/drm_modes.h#L278)来判断，而不是转换成字符串

2023-07-10 08:13 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +		}
可能也要加上`mode->flag`有没有[`DRM_MODE_FLAG_INTERLACE`](https://elixir.bootlin.com/linux/latest/source/include/drm/drm_modes.h#L278)的检查

2023-07-10 11:57 UTC, RadxaYuntian requested changes

2023-07-10 11:57 UTC, RadxaYuntian commented on drivers/gpu/drm/bridge/synopsys/dw-hdmi.c
> +					}
`DRM_MODE_FLAG_INTERLACE`的`mode`我们直接忽略的，这个分支可以不要

2023-07-11 03:51 UTC, RadxaYuntian approved these changes

2023-07-11 06:55 UTC, merged