adjust opp-table for rk356x-t
radxa/kernel pull request #166
Opened 2023-07-25 02:23 UTC by Radxa-Alvin

2023-07-25 02:48 UTC, RadxaYuntian requested changes

2023-07-25 02:48 UTC, RadxaYuntian commented on drivers/soc/rockchip/rockchip-cpuinfo.c
> +cell = nvmem_cell_get(dev, "performance");
缩进

2023-07-25 02:49 UTC, RadxaYuntian commented
可以把我设置为reviewer但不要设为assignee。Rockchip内核这边还是Stephen负责

2023-07-26 02:13 UTC, RadxaStephen approved these changes

2023-07-26 06:25 UTC, merged