Fix rock 3c/cm3s USB wakeup problem
radxa/kernel pull request #171
Opened 2023-08-02 08:55 UTC by vamrs-feng

The current rock 3c/ cm3s io has the problem that some usb ports wake up automatically 
after the system is suspended. It is necessary to temporarily disable the wake-up function 
of a certain USB port, or not use the problematic USB port.

2023-08-02 09:44 UTC, RadxaYuntian requested changes

2023-08-02 09:44 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3s-io.dts
CM3S不能使用同样的方法么？

2023-08-02 09:44 UTC, RadxaYuntian commented on drivers/phy/rockchip/phy-rockchip-inno-usb2.c
> +	bool disable_wake;
变量名要对齐

2023-08-02 09:44 UTC, RadxaYuntian commented on drivers/phy/rockchip/phy-rockchip-inno-usb2.c
>  			ret = rockchip_usb2phy_enable_line_irq(rphy, rport, true);
```suggestion
		// Only enable interrupt during suspend if no disable_wake was defined
		ret = rockchip_usb2phy_enable_line_irq(rphy, rport, !rport->disable_wake);
```

2023-08-02 10:09 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3s-io.dts
应该可以，但是CM3S没有用到这个口

2023-08-02 10:51 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3s-io.dts
是CM3S没有暴露出这个口还是CM3S IO没有实现这个口？如果是前者需要在核心板级dts添加disable_wake

2023-08-02 10:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3s-io.dts
我的意思是后者，CM3S包含对应口的情况下

2023-08-03 07:28 UTC, RadxaYuntian requested changes

2023-08-03 07:28 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3s-io.dts
>  	phy-supply = <&vcc5v0_usb20>;
```suggestion
```
既然板上没有支持那也不需要配置供电

2023-08-03 09:11 UTC, merged