cm3 io: add wifi and bluetooth
radxa/kernel pull request #177
Opened 2023-08-07 06:23 UTC by vamrs-feng

2023-08-07 06:42 UTC, RadxaYuntian reviewed
这些不是应该定义在核心板级文件里面么？

2023-08-07 07:37 UTC, vamrs-feng commented
确实

2023-08-22 02:42 UTC, RadxaYuntian requested changes

2023-08-22 02:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3.dtsi
> +	rockchip,default-sample-phase=<90>;
```suggestion
	rockchip,default-sample-phase = <90>;
```

2023-08-22 02:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3.dtsi
> +	sd-uhs-sdr104;
sdio能定义这个属性么？

2023-08-23 06:35 UTC, RadxaYuntian commented
可能也要测试一下wifi和蓝牙的共同使用是否会有问题

2023-08-23 07:30 UTC, vamrs-feng commented
1. 提高max-frequency，速度是达标了,不过可能和3C一样需要测试稳定性；
2. 也存在连接wifi后，蓝牙无法扫描到的问题；

2023-08-29 09:23 UTC, merged