mmc: sdhci-of-dwcmshc:  improve HS400ES compatibility for some eMMC devices
radxa/kernel pull request #184
Opened 2023-08-16 03:02 UTC by yjxyx

2023-08-16 08:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a.dts
是不是revert 12df165bfc4e6eaf036bb72304ca61fb55290d2f 更好一点？另外最初的定义里面是没有HS200的，是不是需要保留？

2023-08-16 08:38 UTC, RadxaYuntian commented
另外修改PR可以直接在你这个分支上继续提交，或者force push，不需要关闭PR

2023-08-16 09:20 UTC, yjxyx commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a.dts
直接revert有些项目的clk频率和HS400模式参数设置的有问题.   HS200和HS400模式驱动是自适应的,可以配置多个的.

2023-08-16 09:56 UTC, RadxaYuntian requested changes
这些改动可以在GitHub PR页面的Files changed标签页里批量选中提交

2023-08-16 09:56 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-radxa-cm5-io.dts
> +	mmc-hs200-1_8v;
```suggestion
```
总线参数应该是在核心板配好，然后底板只需要启用就可以

2023-08-16 09:56 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-radxa-cm5.dtsi
```suggestion

&sdhci {
	bus-width = <8>;
	no-sdio;
	no-sd;
	non-removable;
	max-frequency = <200000000>;
	mmc-hs400-1_8v;
	mmc-hs400-enhanced-strobe;
	mmc-hs200-1_8v;
};
```

2023-08-16 09:56 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-radxa-nx5-io.dts
```suggestion

&sdhci {
	status = "okay";
};
```
核心板没有开启总线，需要在底板里开启

2023-08-16 10:40 UTC, yjxyx commented
>操作失误 重新提交

2023-08-16 10:48 UTC, RadxaYuntian approved these changes
一般PR提交者不要主动去resolve发现的问题，是审核者检查最新提交后再resolve的。
例外是应用代码修改建议时，GitHub会自动resolve，这是没问题的。

2023-08-17 06:03 UTC, RadxaStephen approved these changes

2023-08-17 06:11 UTC, merged