dts: rockchip: add Radxa E61 support
radxa/kernel pull request #189
Opened 2023-08-18 08:29 UTC by Radxa-Alvin

2023-08-18 09:29 UTC, RadxaYuntian requested changes

2023-08-18 09:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +	status = "disabled";
为什么这个是禁用的？

2023-08-18 09:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +	status="okay";
```suggestion
	status = "okay";
```

2023-08-18 09:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +&sdmmc0 {
sdmmc的定义可以放到cm3i.dtsi，e61.dts只把status = okay

2023-08-18 09:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +&gmac0 {
gmac0的定义可以放到cm3i.dtsi，e61.dts只把status = okay

2023-08-18 09:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +	rgmii_phy0: phy@0 {
rgmii_phy0的定义可以放到cm3i.dtsi

2023-08-18 09:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +	hdmi_sound: hdmi-sound {
hdmi_sound的定义可以放到cm3i.dtsi，e61.dts只把status = okay

2023-08-21 02:09 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +	status = "disabled";
B-KEY默认开SATA

2023-08-21 02:15 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +&gmac0 {
这是底板的phy 还是放底板的dts上好点

2023-08-22 03:37 UTC, RadxaYuntian requested changes

2023-08-22 03:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-cm3i.dtsi
> +			vcc_ddr: DCDC_REG3 {
没有设定电压？

2023-08-22 03:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-cm3i.dtsi
> +};
是不是需要加上HS400ES相关的定义？

2023-08-22 03:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-cm3i.dtsi
> +	};
```suggestion
		spi-rx-bus-width = <4>;
	};
```
partitions定义是不需要的

2023-08-22 03:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +		states = <100000 0x0
这个电压确认是对的？0.1v？如果只是一个开3.3v关0v的regulator就应该用`compatible = "regulator-fixed";`

2023-08-22 03:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +&gmac0 {
哪核心板怎么还有个gmac1

2023-08-22 03:47 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-cm3i.dtsi
> +			vcc_ddr: DCDC_REG3 {
看其他356X是这么配的

2023-08-22 06:16 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +&gmac0 {
核心板也有个phy

2023-08-22 06:22 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-cm3i.dtsi
> +};
这个我看其他板子都没加就先不加吧

2023-08-22 06:58 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +&gmac0 {
这gmac0应该是rk3568.dtsi里面定义的吧？SoC应该是支持两个gmac的。应该是在核心板把SoC支持的东西都配好，在底板打开就可以了

2023-08-22 07:01 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +&gmac0 {
核心板上没有的东西就不配了吧, 都是include 3568.dtsi的

2023-08-22 07:03 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +	rgmii_phy0: phy@0 {
底板上的phy跟着底板的DTS走好点吧

2023-08-22 07:09 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/rk3568-radxa-e61.dts
> +		states = <100000 0x0
这里是没问题的

2023-08-22 08:09 UTC, RadxaYuntian approved these changes

2023-08-22 08:11 UTC, merged