Radxa CM3 Rpi CM4 IO: add EMC2301
radxa/kernel pull request #192
Opened 2023-08-23 06:40 UTC by nascs

2023-08-23 07:19 UTC, RadxaYuntian requested changes

2023-08-23 07:19 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +		channel@1 {
1. 2301只有一个channel吧？
2. 需要把风扇也配置上

2023-08-23 07:19 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +			pwm-min = /bits/ 8 <0>;
```suggestion
			pwm-min = <0>;
```
根据 02e34fc6854c8c37d42fc422f2b5479123392893 所说这里及后面应该可以去掉u8。dts默认编译成u16，不影响驱动内读取u8

2023-08-24 09:01 UTC, RadxaYuntian requested changes

2023-08-24 09:01 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +		map3 {
```suggestion
		map2 {
```
默认只定义到了map1

2023-08-24 09:01 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +		map4 {
```suggestion
		map3 {
```

2023-08-24 10:11 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +			pwm-min = /bits/ 8 <0>;
这个改一下试试看

2023-08-25 01:31 UTC, nascs commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +			pwm-min = /bits/ 8 <0>;
可以这么改的

2023-08-25 02:04 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +			pwm-min = /bits/ 8 <0>;
上面还有个cooling-level啊，一起改了

2023-08-25 02:40 UTC, RadxaYuntian approved these changes

2023-08-25 03:14 UTC, nascs commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +			pwm-min = /bits/ 8 <0>;
这两个这么改，都没问题的， 风扇转速会随着温度的增减而增减

2023-08-25 03:16 UTC, nascs commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +			pwm-min = /bits/ 8 <0>;
做了压测， 温度升高的时候，转速更快，温度降下来的时候，转速也跟着减

2023-08-25 07:59 UTC, RadxaStephen approved these changes

2023-08-25 08:05 UTC, merged