rockchip_linux_defconfig: enable emc2305 sensors
radxa/kernel pull request #198
Opened 2023-08-30 08:47 UTC by nascs

Signed-off-by: Nascs Fang <nascs@radxa.com>

2023-08-30 09:29 UTC, RadxaYuntian requested changes

2023-08-30 09:29 UTC, RadxaYuntian commented on arch/arm64/configs/rockchip_linux_defconfig
1. 文件结尾要有空格
2. 建议是用make menuconfig先开启需要选项后，用make savedefconfig重新生成更新后的defconfig，然后再替换对应文件

2023-09-01 07:47 UTC, nascs commented on arch/arm64/configs/rockchip_linux_defconfig
我生成的 defconfig 和 rockchip_linux_defconfig 差异会有点大

2023-09-04 10:28 UTC, RadxaYuntian commented on arch/arm64/configs/rockchip_linux_defconfig
那要确保你的内核不是通过我们bsp进行配置的，不然会添加一些额外的配置

2023-09-04 11:30 UTC, nascs commented
CONFIG_DMABUF_DEBUG=y

这个内核配置里面没有

2023-09-06 02:21 UTC, merged