cm3/cm3 io: add rockchip suspend,add spi-flash,fix microphone recording issue
radxa/kernel pull request #202
Opened 2023-09-06 08:59 UTC by vamrs-feng

2023-09-06 09:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3.dtsi
> +		spi-rx-bus-width = <4>;
这两个好像是主线u-boot才需要的，因为驱动有差异

2023-09-06 09:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3.dtsi
> +		spi-max-frequency = <50000000>;
50M测试过么？主线一般都是定义24M

2023-09-06 09:52 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3.dtsi
> +		spi-max-frequency = <50000000>;
直接复制自3C的

2023-09-07 02:58 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3.dtsi
> +		spi-rx-bus-width = <4>;
这个现在是什么状况

2023-09-07 03:18 UTC, RadxaYuntian commented
@vamrs-feng 没别的改动了你再改成ready for review

2023-09-07 03:28 UTC, RadxaYuntian commented
radxa/overlays#170 里禁用的hym8563在底板上已有定义

2023-09-07 07:04 UTC, RadxaYuntian requested changes

2023-09-07 07:04 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> +	num-slots = <1>;
```suggestion
```
驱动并没有支持这一属性。

2023-09-07 09:56 UTC, RadxaYuntian commented
还有别的改动么？没有就改成ready for review

2023-09-07 10:20 UTC, RadxaYuntian approved these changes

2023-09-08 07:30 UTC, merged