dts: radxa cm3 rpi cm4 io: add pcf85063 rtc
radxa/kernel pull request #214
Opened 2023-09-18 06:52 UTC by vamrs-feng

2023-09-18 06:53 UTC, RadxaYuntian requested changes

2023-09-18 06:53 UTC, RadxaYuntian commented on arch/arm64/configs/rockchip_linux_defconfig
> +CONFIG_RTC_DRV_PCF85063=y
结尾空行

2023-09-18 07:00 UTC, RadxaYuntian requested changes

2023-09-18 07:00 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts
> +		#clock-cells = <0>;
```suggestion
```
文档里面这个应该是子节点的属性：https://www.kernel.org/doc/Documentation/devicetree/bindings/rtc/nxp%2Cpcf85063.txt

2023-09-18 07:09 UTC, RadxaYuntian commented on arch/arm64/configs/rockchip_linux_defconfig
> +
你这是多了个空行吧？文件结尾应该只有一个空行

2023-09-18 07:24 UTC, RadxaYuntian approved these changes

2023-09-18 12:49 UTC, RadxaStephen commented
Please modify rockchip_linux_defconfig via make menuconfig.

2023-09-20 04:08 UTC, RadxaStephen commented
Usually we have at least three kinds of commits, dts, driver, defconfig.
We should have separate commits for dts, driver, defconfig.

Here, please provide one commit for dts and another one commit for defconfig.

2023-09-20 09:10 UTC, merged