drivers/rtc: hym8563: Add failure retry
radxa/kernel pull request #239
Opened 2023-11-08 12:26 UTC by vamrs-feng

If the device is not ready, the initialization may fail. A mechanism for multiple delayed retries is added.

2023-11-08 12:43 UTC, RadxaYuntian requested changes
你可以先尝试一下这个修改。@Ken-Vamrs 有这方面的经验

2023-11-08 12:43 UTC, RadxaYuntian commented on drivers/rtc/rtc-hym8563.c
>  		return ret;
```suggestion
		return -EPROBE_DEFER;
```
应该是保持原来的函数调用不变，只是告诉系统让他之后重新尝试probe，而不是自己把这里卡死

2023-11-09 02:53 UTC, vamrs-feng commented on drivers/rtc/rtc-hym8563.c
>  		return ret;
这样是想让PMU上的RTC不会先注册，如果返回-EPROBE_DEFER，会不会被PMU-RTC给先注册了呢。

2023-11-09 02:55 UTC, RadxaYuntian commented on drivers/rtc/rtc-hym8563.c
>  		return ret;
那去改驱动给pmu rtc加个开关的flag啊……从根源解决问题

2023-11-10 09:40 UTC, RadxaYuntian requested changes

2023-11-10 09:40 UTC, RadxaYuntian commented on drivers/rtc/rtc-hym8563.c
> +		return -EPROBE_DEFER;
这边应该不用改吧？我只是以为你这里之前是不会重试初始化的。但现在澄清了需求不是这个后，驱动应该有做重新初始化的工作

2023-11-10 10:40 UTC, RadxaYuntian approved these changes

2023-11-16 10:03 UTC, merged