Fix cm5 and 5b+ typec cannot find u disk.
radxa/kernel pull request #250
Opened 2023-12-01 11:41 UTC by Ken-Vamrs

2023-12-01 11:50 UTC, RadxaYuntian reviewed
5b的最后三个commit是为了实现什么目的？

2023-12-01 11:54 UTC, Ken-Vamrs commented
> 5b的最后三个commit是为了实现什么目的？

是5B原先有两个个commit影响了cm5/5b+ 的 typec usb识别，然后加两个属性给5b指定使用原先那两个修改

2023-12-01 11:58 UTC, RadxaYuntian requested changes

2023-12-01 11:58 UTC, RadxaYuntian commented on drivers/usb/typec/tcpm/tcpm.c
> +	fixed_typec_miss_data = fwnode_property_read_bool(fwnode, "fixed-typec-miss-data");
要修改struct tcpm_port的定义，把两个新增的变量加进去，而不是使用全局变量

2023-12-04 02:58 UTC, Ken-Vamrs commented on drivers/usb/typec/tcpm/tcpm.c
> +	fixed_typec_miss_data = fwnode_property_read_bool(fwnode, "fixed-typec-miss-data");
好的，已修改

2023-12-04 03:25 UTC, RadxaYuntian requested changes

2023-12-04 03:25 UTC, RadxaYuntian commented on drivers/usb/typec/tcpm/tcpm.c
> +		if ((port->explicit_contract && !port->fixed_typec_miss_data) || (port->explicit_contract && port->data_role == TYPEC_HOST))
```suggestion
		if ((port->explicit_contract) && (!port->fixed_typec_miss_data || port->data_role == TYPEC_HOST))
```
这样可读性更好

2023-12-04 03:25 UTC, RadxaYuntian commented on drivers/usb/typec/tcpm/tcpm.c
> +
```suggestion
```

2023-12-04 06:20 UTC, RadxaYuntian approved these changes

2023-12-04 13:19 UTC, merged