add dts for different configurations
radxa/kernel pull request #255
Opened 2023-12-08 02:11 UTC by Radxa-Alvin

2023-12-08 02:46 UTC, RadxaYuntian requested changes
另外现有的zero3.dts和3c.dts需要改成使用对应的dtsi以及配置好当前所支持的wifi/以太网，避免代码重复

2023-12-08 02:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/Makefile
> +dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-rock-3c-ap6256.dtbo
是dtb

2023-12-08 02:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/Makefile
> -dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-radxa-zero3.dtb
原来的zero3.dtb必须保留，不然现有用户升级后无法启动

2023-12-08 03:05 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/Makefile
> +dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-rock-3c-ap6256.dtbo
目前没修改原来的DTS  新增了 去除差异配置的 DTSI，原来的DTS 还是保持不动吧  这样老的板子不会有影响

2023-12-08 03:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/Makefile
> +dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-rock-3c-ap6256.dtbo
主要是我们时不时会有一些设备树的修改，现在你这样就需要改两个地方

2023-12-08 03:18 UTC, Radxa-Alvin commented on arch/arm64/boot/dts/rockchip/Makefile
> +dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-rock-3c-ap6256.dtbo
把目前的rock3c.dts改为 rock3c.dtsi 再新增一个空白的rock3c.dts引用rock3c.dtsi吗

2023-12-08 03:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/Makefile
> +dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-rock-3c-ap6256.dtbo
3c.dtsi是共通部分，里面是没有wifi定义的。ap wifi定义放到rock-3c.dts

2023-12-11 02:59 UTC, RadxaStephen approved these changes

2023-12-11 04:01 UTC, RadxaYuntian requested changes
另外需要把zero3.dts也仿照3c.dts改成使用dtsi

2023-12-11 04:01 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-zero-3e.dts
> +	compatible = "radxa,zero-3e","radxa,zero3", "rockchip,rk3566";
```suggestion
	compatible = "radxa,zero-3e", "radxa,zero3", "rockchip,rk3566";
```

2023-12-11 04:01 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-zero-3w-aic8800ds2.dts
> +
这些应该在dtsi里面就禁用了，然后只在3e里面打开

2023-12-11 04:01 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-zero-3w-ap6212.dts
> +
3e

2023-12-11 08:26 UTC, merged

2023-12-11 09:09 UTC, RadxaYuntian commented
以太网的定义应该只放在3e.dts而不是zero3.dtsi
zero3.dts也没转换成使用zero3.dtsi

2023-12-11 10:02 UTC, Radxa-Alvin commented
前面不是说把配置写 dtsi 么然后在 3e enable么，原来的DTS 同时使能了 wifi 和以太网，现在的dtsi 把以太网相关的节点先关掉了，有点差异，先这样用着吧，后面板子硬件有修改再做改动吧

2023-12-11 10:04 UTC, RadxaYuntian commented
说的是dtsi不写以太网也不写wifi