modify radxa e25 dts
radxa/kernel pull request #270
Opened 2024-01-19 08:48 UTC by Radxa-Alvin

2024-01-19 12:07 UTC, RadxaYuntian requested changes
建议用heartbeat，这样用户可以知道系统是否仍然存活

2024-01-22 02:29 UTC, Radxa-Alvin commented
进到系统后交给rsetup接管了，内核启动阶段亮着就好了吧，而且这个闪起来感觉也不好看

2024-01-22 07:39 UTC, RadxaYuntian commented
主要是现在如果启动有问题用户是无法发现的

2024-01-22 08:14 UTC, Radxa-Alvin commented
启动有问题的话进不到rsetup 设置的灯效，如果灯效一直没变化也说明内核启动有问题，跟heartbeat 提示效果都差不多吧，只是觉得 heartbeat 这么多灯闪起来不好看

2024-01-22 08:18 UTC, RadxaYuntian commented
有时候是内核不能启动，这时候灯会定住。有时候是比如文件系统出问题或者什么配置问题，这时候内核还能运行，但无法加载服务，这时候就可以用heartbeat。

2024-01-29 02:08 UTC, RadxaStephen commented
Applied to linux-5.10-gen-rkr4.1 branch.

2024-01-29 02:08 UTC, closed without merging