update rock5itx dts
radxa/kernel pull request #275
Opened 2024-02-18 07:50 UTC by Ken-Vamrs

2024-02-19 03:23 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5-itx.dts
> +			connect = <&vp1_out_hdmi1>;
这里的logo啥的应该我们没用到吧

2024-02-19 03:25 UTC, RadxaYuntian requested changes

2024-02-19 03:25 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5-itx.dts
> +			connect = <&vp1_out_hdmi1>;
我检查了一下，route_hdmi1在rk3588.dtsi里面应该已经有相同的定义了。可以把这些删掉

2024-02-19 08:58 UTC, RadxaYuntian approved these changes

2024-02-20 10:35 UTC, RadxaStephen commented
Applied to linux-5.10-gen-rkr3.4 branch.

2024-02-20 10:35 UTC, closed without merging