add allnet 5 inch display
radxa/kernel pull request #280
Opened 2024-02-27 12:17 UTC by Ken-Vamrs

2024-02-28 02:48 UTC, RadxaYuntian requested changes

2024-02-28 02:48 UTC, RadxaYuntian commented on drivers/gpu/drm/panel/panel-raspits-tc358762.c
> -		/* sentinel */
这个注释保留到下面，不要改动不相关的代码

2024-02-28 02:48 UTC, RadxaYuntian commented on drivers/gpu/drm/panel/panel-raspits-tc358762.c
> +		.compatible = "raspits,tc358762,5inch",
```suggestion
		.compatible = "raspits,tc358762-5inch",
```
格式好像没有多个逗号吧：https://elinux.org/Device_Tree_Usage#Understanding_the_compatible_Property

2024-02-28 02:48 UTC, RadxaYuntian commented on drivers/gpu/drm/panel/panel-raspberrypi-touchscreen.c
> +		.htotal = 800 + 1 + 5 + 40,
需要解释一下这个改动。另外是不是会有两个屏幕用这个驱动，会有影响么？

2024-02-28 06:50 UTC, Ken-Vamrs commented
已重新修改提交

2024-02-28 09:03 UTC, RadxaYuntian requested changes

2024-02-28 09:03 UTC, RadxaYuntian commented on drivers/gpu/drm/panel/panel-raspits-tc358762.c
> +
```suggestion
```

2024-02-29 08:53 UTC, RadxaStephen commented
Added to branch linux-5.10-gen-rkr3.4.

2024-02-29 08:53 UTC, closed without merging