drivers: imx219: set 3280*2464 resolution by default
radxa/kernel pull request #282
Opened 2024-03-04 11:28 UTC by Radxa-Alvin

2024-03-05 03:00 UTC, RadxaYuntian requested changes

2024-03-05 03:00 UTC, RadxaYuntian commented on drivers/media/i2c/imx219.c
>  	/* 1920 * 1080 by default */
注释要更新

2024-03-05 03:00 UTC, RadxaYuntian commented on drivers/media/i2c/imx219.c
> +	// priv->crop_rect.left = 680;
用if判断cur_mode，如果是1080p再设置crop_rect。这样如果之后需要修改默认分辨率可以避免漏掉这里

2024-03-05 03:21 UTC, Radxa-Alvin commented on drivers/media/i2c/imx219.c
> +	// priv->crop_rect.left = 680;
相关的效果文件已将修改到了 3280*2464分辨率，应该不会再改小分辨率了，当前已经测试验证完了先不做修改了

2024-03-13 11:54 UTC, RadxaStephen commented
Added to branch linux-5.10-gen-rkr3.4.

2024-03-13 11:55 UTC, closed without merging