iwlwifi: mvm: fix load pnvm error when firmware is ty-a0-gf-a0-59.ucode
radxa/kernel pull request #288
Opened 2024-03-25 11:44 UTC by CodeChenL

iwlwifi: mvm: fix load pnvm error when firmware is ty-a0-gf-a0-59.ucode

2024-03-25 11:48 UTC, RadxaYuntian requested changes

2024-03-25 11:48 UTC, RadxaYuntian commented on drivers/net/wireless/intel/iwlwifi/mvm/fw.c
>  	ret = iwl_pnvm_load(mvm->trans, &mvm->notif_wait);
不加载pnvm不是应该跳过这个函数么

2024-03-25 11:53 UTC, CodeChenL commented on drivers/net/wireless/intel/iwlwifi/mvm/fw.c
>  	ret = iwl_pnvm_load(mvm->trans, &mvm->notif_wait);
跳过会报错，提示加载固件超时，我这里的操作是受到了 https://github.com/radxa/kernel/blob/513eba37f50fcb879f77ebf885d6c471932c7d4f/drivers/net/wireless/intel/iwlwifi/fw/pnvm.c#L264 的启发

2024-03-26 02:01 UTC, RadxaYuntian approved these changes
看看3a是不是也有这个问题，有的话给rkr4.1分支也提一个PR

2024-04-02 02:11 UTC, StephenInVamrs commented
Added to branch linux-5.10-gen-rkr3.4.

2024-04-02 02:11 UTC, closed without merging