arm64: dts: rockchip: radxa e20c: add leds
radxa/kernel pull request #317
Opened 2024-05-15 07:02 UTC by lsj123lsjlsj

arm64: dts: rockchip: radxa e20c: add sys/wan/lan leds

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-05-15 09:40 UTC, RadxaYuntian requested changes

2024-05-15 09:40 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3528-radxa-e20c.dts
> +			linux,default-trigger = "none";
https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/intel/ixp/intel-ixp42x-dlink-dsm-g600.dts#L51

2024-05-15 09:43 UTC, lsj123lsjlsj commented on arch/arm64/boot/dts/rockchip/rk3528-radxa-e20c.dts
> +			linux,default-trigger = "none";
这个尝试过trigger为netdev 并且在sys写入到trigger了 但是灯没闪烁 Stephen说先基于这个提交

2024-05-15 10:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3528-radxa-e20c.dts
> +			linux,default-trigger = "none";
要在sysfs里面配置吧？
https://kernel.googlesource.com/pub/scm/linux/kernel/git/nvdimm/nvdimm/+/libnvdimm-for-next/Documentation/ABI/testing/sysfs-class-led-trigger-netdev
https://gist.github.com/FrankWu100/25779214ea0981f7d3095014a815a10f

2024-05-21 06:36 UTC, RadxaYuntian requested changes
squash提交

2024-05-21 07:06 UTC, RadxaYuntian approved these changes

2024-05-21 14:12 UTC, RadxaStephen commented
Added it to branch linux-5.10-gen-rkr4.1.

2024-05-21 14:12 UTC, closed without merging