drivers: net: ethernet: realtek: r8168: modify led status
radxa/kernel pull request #322
Opened 2024-05-21 09:17 UTC by lsj123lsjlsj

drivers: net: ethernet: realtek: r8168: modify led status

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-05-21 09:48 UTC, RadxaYuntian requested changes

2024-05-21 09:48 UTC, RadxaYuntian commented on drivers/net/ethernet/realtek/r8168/r8168_n.c
> +
```suggestion
        RTL_W16(tp, CustomLED, RADXA_CUSTOM_LED);
        tp->NicCustLedValue = RTL_R16(tp, CustomLED);
```
不过最好是添加一个设备树属性来override这个值吧

2024-05-21 09:48 UTC, RadxaYuntian commented on drivers/net/ethernet/realtek/r8168/r8168_n.c
> +#define RADXA_CUSTOM_LED 0x0c7f
```suggestion
// Definition: https://blog.csdn.net/Yongheng6/article/details/134659910
#define RADXA_CUSTOM_LED 0x0c7f
```

2024-05-21 10:14 UTC, RadxaSongjun commented on drivers/net/ethernet/realtek/r8168/r8168_n.c
> +#define RADXA_CUSTOM_LED 0x0c7f
if(tp->NicCustLedValue != RADXA_CUSTOM_LED)加入这个判断是因为sfuse不能烧入太多次而做的一个检测机制，设备树override我试试看

2024-05-21 10:59 UTC, RadxaYuntian commented on drivers/net/ethernet/realtek/r8168/r8168_n.c
> +#define RADXA_CUSTOM_LED 0x0c7f
这个应该是写寄存器，不是efuse啊

2024-06-04 06:40 UTC, RadxaStephen commented
Please check this patch. https://github.com/coolsnowwolf/lede/blob/master/package/lean/r8168/patches/100-add-LED-configuration-from-OF.patch

2024-06-19 03:44 UTC, closed without merging

2024-06-19 03:44 UTC, RadxaStephen commented
I change the code like removing unnecessary space and change the git message.

Added to branch linux-5.10-gen-rkr4.1.