arm64: rockchip_linux_defconfig: enable CONFIG_USB_MASS_STORAGE
radxa/kernel pull request #331
Opened 2024-06-04 03:36 UTC by RadxaMitchell

The g_mass_storage driver is required when using USB UMS.
Enable CONFIG_USB_MASS_STORAGE so that the g_mass_storage driver can be compiled into the kernel.

2024-06-04 03:44 UTC, RadxaYuntian requested changes

2024-06-04 03:44 UTC, RadxaYuntian commented on arch/arm64/configs/rockchip_linux_defconfig
> +CONFIG_USB_MASS_STORAGE=y
```suggestion
CONFIG_USB_MASS_STORAGE=m
```

2024-06-04 06:24 UTC, RadxaYuntian approved these changes

2024-06-05 11:20 UTC, RadxaStephen commented
Added it to branch linux-6.1-stan-rkr1.

2024-06-05 11:20 UTC, closed without merging