media: i2c: imx219: set 3280*2464 resolution by default
radxa/kernel pull request #345
Opened 2024-07-04 06:36 UTC by Ken-Vamrs

Update initialization register to support 3280x2464 resolution

2024-07-04 06:40 UTC, RadxaYuntian requested changes

2024-07-04 06:40 UTC, RadxaYuntian commented on drivers/media/i2c/imx219.c
>  	/* 1920 * 1080 by default */
```suggestion
	/* 3280 * 2464 by default */
```

2024-07-04 06:40 UTC, RadxaYuntian commented on drivers/media/i2c/imx219.c
> +	// priv->crop_rect.top = 692;
```suggestion
	if (priv->cur_mode == &supported_modes[0]) {
		priv->crop_rect.left = 680;
		priv->crop_rect.top = 692;
	}
```
指针能不能这样对比不太记得了

2024-07-04 07:07 UTC, Ken-Vamrs commented on drivers/media/i2c/imx219.c
> +	// priv->crop_rect.top = 692;
这么写应该没问题，不过直接注释掉就好了，有这个可能导致切换分辨率画面异常

2024-07-04 07:15 UTC, RadxaYuntian approved these changes

2024-07-04 07:15 UTC, RadxaYuntian commented on drivers/media/i2c/imx219.c
> +	// priv->crop_rect.top = 692;
那其实不如直接删掉

2024-07-04 07:18 UTC, Ken-Vamrs commented on drivers/media/i2c/imx219.c
> +	// priv->crop_rect.top = 692;
删

2024-07-04 07:21 UTC, RadxaYuntian approved these changes

2024-07-05 07:41 UTC, RadxaStephen commented
Added to branch linux-5.10-gen-rkr4.1.

2024-07-05 07:41 UTC, closed without merging