To fix cm3 io boot break and modify some supply attribute value
radxa/kernel pull request #354
Opened 2024-08-08 10:48 UTC by CodeChenL

2024-08-08 10:55 UTC, RadxaYuntian requested changes
另外signoff用公司邮箱

2024-08-08 10:55 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
这个删了你有检查功能还能用么，另外不是说只用改vpcie3v3-supply就可以了么

2024-08-08 10:59 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
vpcie3v3-supply不影响启动，只有pinctrl-names影响启动，可以通过转接板正常使用nvme硬盘

2024-08-08 11:02 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
上游内核的定义都是有这个属性的，我对这个改动持保留态度：https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/rockchip/rk3568-rock-3b.dts#L536

2024-08-09 02:10 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
可是我们的[radxa:linux-5.10-gen-rkr4.1](https://github.com/radxa/kernel/tree/linux-5.10-gen-rkr4.1)都是不带pinctrl-names的

2024-08-09 02:37 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
我看原理图这个ch482d 切换的应该只是信号源，应该不涉及电源，所以这个 supply 是不是不改好点呢

2024-08-09 03:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
> 可是我们的[radxa:linux-5.10-gen-rkr4.1](https://github.com/radxa/kernel/tree/linux-5.10-gen-rkr4.1)的356x pcie节点都是不带pinctrl-names的

因为也没指定pinctrl-0啊，这两个是一起的

> 我看原理图这个ch482d 切换的应该只是信号源，应该不涉及电源，所以这个 supply 是不是不改好点呢

也可以

2024-08-09 03:21 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
> > 可是我们的[radxa:linux-5.10-gen-rkr4.1](https://github.com/radxa/kernel/tree/linux-5.10-gen-rkr4.1)的356x pcie节点都是不带pinctrl-names的
> 
> 因为也没指定pinctrl-0啊，这两个是一起的
> 
> > 我看原理图这个ch482d 切换的应该只是信号源，应该不涉及电源，所以这个 supply 是不是不改好点呢
> 
> 也可以

这几个也都有pinctrl-0，但是没有pinctrl-names
https://github.com/radxa/kernel/blob/7f20821f6223539d74fbdcd146ee02d0ec64ff30/arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-rpi-cm4-io.dts#L114
https://github.com/radxa/kernel/blob/7f20821f6223539d74fbdcd146ee02d0ec64ff30/arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3s-io.dts#L268

2024-08-09 06:20 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3566-radxa-cm3-io.dts
> -	pinctrl-names = "default";
看了下names的确是可选的：https://www.kernel.org/doc/Documentation/devicetree/bindings/pinctrl/pinctrl-bindings.txt

2024-08-09 06:21 UTC, RadxaYuntian reviewed
supply相关的改动还是去掉吧，想了想万一系统把对应的设备关了那信号就连接错了

2024-08-09 06:49 UTC, RadxaYuntian approved these changes

2024-08-13 09:57 UTC, RadxaStephen commented
```Author: CodeChenL <2540735020@qq.com>```

改一下这里的邮箱为 Radxa 邮箱

2024-08-13 11:27 UTC, CodeChenL commented
> `Author: CodeChenL <2540735020@qq.com>`
> 
> @CodeChenL 改一下这里的邮箱为 Radxa 邮箱

你看的是不是不是最新的commit，我这显示是公司的
![image](https://github.com/user-attachments/assets/1a8bc0d6-0dbb-4938-8f36-a9c92969e52e)

2024-08-13 11:32 UTC, RadxaStephen commented
```
Author: CodeChenL <2540735020@qq.com>
Date:   Thu Aug 8 18:40:05 2024 +0800

    arm64: dts: rockchip: cm3io: remove pcie2x1 pinctrl-names
    
    To fix boot break
    
    Signed-off-by: ChenJiali <chenjiali@radxa.com>
```

2024-08-13 12:00 UTC, RadxaStephen commented
Added to branch linux-5.10-gen-rkr4.1.

2024-08-13 12:00 UTC, closed without merging