arm64: rockchip: dts: add rk3588 rock 5t
radxa/kernel pull request #357
Opened 2024-08-27 02:13 UTC by Ken-Vamrs

2024-08-27 03:18 UTC, RadxaYuntian requested changes

2024-08-27 03:18 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +	em05_modem: em05-modem {
产品上有自带em05？

2024-08-27 03:18 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +			default-state = "on";
```suggestion
```
这个应该没有定义的意义

2024-08-27 03:38 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +	em05_modem: em05-modem {
配件即插即用

2024-08-27 08:31 UTC, RadxaYuntian approved these changes

2024-08-28 02:32 UTC, RadxaYuntian requested changes

2024-08-28 02:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a-spi.dts
> +
compatible要加一个类似"radxa,rock-5a-spi"来识别
model可能也要加个后缀

2024-08-28 02:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a.dts
> +			default-state = "on";
```suggestion
```

2024-08-28 02:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a.dts
> +			default-state = "on";
```suggestion
```

2024-08-28 02:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a.dts
> +	    };
wifibt的缩进不对

2024-08-28 03:22 UTC, RadxaYuntian requested changes

2024-08-28 03:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a-spi.dts
> +	compatible = "radxa,rock-5a", "radxa,rock-5a-spi", "rockchip,rk3588";
```suggestion
	compatible = "radxa,rock-5a-spi", "radxa,rock-5a", "rockchip,rk3588";
```
越具体的需要放到越前面

2024-08-28 03:44 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/rk3588s-rock-5a-spi.dts
> +	compatible = "radxa,rock-5a", "radxa,rock-5a-spi", "rockchip,rk3588";
好的

2024-08-29 02:46 UTC, merged