Fix intermittent playback through browser when force headphone output.
radxa/kernel pull request #372
Opened 2024-10-25 06:45 UTC by Ken-Vamrs

2024-10-25 06:50 UTC, RadxaYuntian requested changes

2024-10-25 06:50 UTC, RadxaYuntian commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
缩进不对，看不出你到底改了啥

2024-10-25 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +			gpios = <&gpio0 RK_PA0 GPIO_ACTIVE_HIGH>;
这是硬件改版还是写错了？

2024-10-25 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +		"", "", "", "PIN_37",
这是硬件改版还是之前忘了？

2024-10-25 06:51 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +			gpios = <&gpio0 RK_PA0 GPIO_ACTIVE_HIGH>;
硬件改版

2024-10-25 06:56 UTC, Ken-Vamrs commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
从5.10内核抄过来的，差别有点大，对着改没改好。
优化了不断暂停播放问题，以及上电时的哒哒声

2024-10-25 06:58 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +			gpios = <&gpio0 RK_PA0 GPIO_ACTIVE_HIGH>;
之前的版本有出售过么？

2024-10-25 07:03 UTC, RadxaYuntian commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
其实可能是我们的alsa config的问题：https://github.com/radxa-pkg/radxa-alsa-config/blob/main/src/alsa/ucm2/conf.d/rockchip-es8316/HiFi.conf

2024-10-25 07:05 UTC, RadxaYuntian commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
可能需要参考一下这：https://github.com/alsa-project/alsa-ucm-conf/tree/master/ucm2/Rockchip/es8316
修改这里用上游的config看看：https://github.com/radxa/kernel/pull/372/files#diff-c3cd5181d410bdbe1149937d61d39c8a36b22851f50caf8e22d54ba114245196R118

2024-10-25 07:09 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/rk3588-rock-5t.dts
> +			gpios = <&gpio0 RK_PA0 GPIO_ACTIVE_HIGH>;
打样阶段  应该只是送过样品

2024-10-28 02:55 UTC, Ken-Vamrs commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
天哥 这个修改没有效果，不得行

2024-10-28 03:44 UTC, RadxaYuntian commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
找armbian的看看？他们也有支持我们用es8316的设备吧

2024-10-28 07:34 UTC, Ken-Vamrs commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
armbian 支持，也没有复现到，但是他不是用rockchip ucm2控制的

2024-10-28 07:35 UTC, RadxaYuntian commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
我们也换成他们那种配置行么

2024-10-31 03:08 UTC, Ken-Vamrs commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
这个能不能合入呢

2024-10-31 03:50 UTC, RadxaYuntian commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
我就感觉我们以后就一直要用这个旧的代码，而不是看问题到底在哪

2024-11-07 12:48 UTC, RadxaStephen commented
Commits for LED, 40-PIn and rtc are merged.

2024-11-08 03:45 UTC, RadxaYuntian commented on sound/soc/codecs/es8316.c
> +    /* Input Lines */
@RadxaStephen 看看到底是不是就先合入这个旧代码了

2024-11-11 10:20 UTC, RadxaStephen commented
Merged.

2024-11-11 10:20 UTC, closed without merging