Stable 4.19 rock3
radxa/kernel pull request #81
Opened 2023-03-24 12:37 UTC by Ken-Vamrs

2023-03-24 13:46 UTC, RadxaYuntian requested changes

2023-03-24 13:46 UTC, RadxaYuntian commented on drivers/misc/rockpi_mcu.c
> +	if (ret == -ENXIO) {
目前有内存泄漏，另外非ENXIO也没有失败的log
```
if (ret < 0) {
    LOG_ERR("init_cmd_check failed, %d\n", ret);
    if (ret == -ENXIO)
        ret = -EPROBE_DEFER;
    goto error;
}
```

2023-03-24 13:46 UTC, RadxaYuntian commented on drivers/input/touchscreen/rockpi_ft5406.c
> +	if (!rockpi_mcu_is_connected()) {
不需要`extern int rockpi_mcu_is_connected(void);`么？

2023-03-27 03:12 UTC, Ken-Vamrs commented on drivers/input/touchscreen/rockpi_ft5406.c
> +	if (!rockpi_mcu_is_connected()) {
这个程序中原来就有extern int rockpi_mcu_is_connected(void);

2023-03-27 03:15 UTC, Ken-Vamrs commented on drivers/misc/rockpi_mcu.c
> +	if (ret == -ENXIO) {
已修改

2023-03-27 06:51 UTC, closed without merging